// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class Primitive {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Primitive(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Primitive.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int plusOne(
    int a,
  ) {
    return _plusOne(
      a,
    );
  }

  late final _plusOnePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int32)>>('plusOne');
  late final _plusOne = _plusOnePtr.asFunction<int Function(int)>();
}
