name: primitives_ffi
description: A super simple example of calling C code from Dart with FFI

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ">=2.12.0  <3.0.0"

ffigen:
  output: 'primitives_bindings.dart'
  headers:
    entry-points:
      - 'primitives_library/primitives.h'

dependencies:
  ffi: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  ffigen: ^4.1.0
  lints: ^1.0.0
  test: ^1.16.0
  test_utils:
    path: ../test_utils
